### ISSUE TITLE
Game crashed with ball fetch

### ISSUE THREAD

**Issue by T0mt4ru** [necro50n3/livelierpokemon#9]
Cobblemon 1.6.1, NeoForge 21.1.115, LivelierPokemon-neoforge-2.0.2+1.21.1

Game crashed after fetching a pokeball

**Crash Report**

[crash-2025-02-19_11.27.07-server.txt](https://github.com/user-attachments/files/18866175/crash-2025-02-19_11.27.07-server.txt)

This was the second time I tried fetching a pokeball. The first time it didn't crash.

**Comment by necro50n3** [comment]
The latest update (2.0.3) should fix this issue now

**Comment by T0mt4ru** [comment]
Cobblemon 1.6.1, NeoForge 21.1.122, LivelierPokemon-neoforge-2.0.3+1.21.1

Still crashes, but I was pushing it.

**When did it crash?**
I tried catching a pokemon a couple of times, growlith brought the ball back nice and simple.
The I thought, what if I am a madman and throw two pokeballs at two different pokemon?

I tossed a pokeball at a Kingler and an unsuspecting krabby.
The game crashed...

**Crash Report**

[crash-2025-02-26_10.29.03-server.txt](https://github.com/user-attachments/files/18981241/crash-2025-02-26_10.29.03-server.txt)

**Comment by necro50n3** [comment]
At a first glance it looks like an incompatibility with servercore's entity activation range feature. Id suggest turning it off for now to see what happens while I work on a fix

**Comment by necro50n3** [comment]
Just released an update that hopefully fixes this. Stress tested it like crazy with no crashes
